import { defineApp } from "convex/server";
import { v } from "convex/values";
import shardedCounter from "@convex-dev/sharded-counter/convex.config.js";
import rateLimiter from "@convex-dev/rate-limiter/convex.config.js";
import staticHosting from "@convex-dev/static-hosting/convex.config.js";
import auth from "@convex-dev/auth/core/convex.config.js";
import passwordProvider from "@convex-dev/auth/providers/password/convex.config.js";
import username from "@convex-dev/auth/username/convex.config.js";

// The static site owns "/" on the .convex.site domain. Any app HTTP routes
// (there are none today) would live under "/api". Auth mounts at "/auth",
// which wins over "/" because the router picks the longest prefix.
const app = defineApp({
  httpPrefix: "/api",
  env: {
    // RS256 key pair the auth component signs sessions with. Generated by
    // `npx @convex-dev/auth` and stored on the deployment.
    AUTH_PRIVATE_KEY: v.string(),
    AUTH_JWKS: v.string(),
  },
});

// Counters that climb toward one million without write contention.
app.use(shardedCounter);

// Per IP and per session posting limits so nobody can flood the wall.
app.use(rateLimiter);

// Convex Auth v2: sessions, plus username + password for the one admin.
app.use(auth, {
  httpPrefix: "/auth",
  env: {
    AUTH_PRIVATE_KEY: app.env.AUTH_PRIVATE_KEY,
    AUTH_JWKS: app.env.AUTH_JWKS,
  },
});
app.use(passwordProvider);
app.use(username);

// Serves the built Vite app straight from Convex storage.
app.use(staticHosting, { httpPrefix: "/" });

export default app;
