// Builds convex/lib/safeWords.ts from the human verified word list at
// https://github.com/The-Best-Codes/safe-words (MIT).
//
// Cleanup rules:
//   strip CRLF, lowercase, drop parenthetical notes and multi word entries,
//   keep only tokens made of a-z and apostrophes, dedupe, sort.
//
// Run: npm run words:build

import { writeFile, mkdir } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const SOURCE =
  "https://raw.githubusercontent.com/The-Best-Codes/safe-words/main/verified-words.txt";

const here = dirname(fileURLToPath(import.meta.url));
const target = resolve(here, "../convex/lib/safeWords.ts");

const response = await fetch(SOURCE);
if (!response.ok) {
  throw new Error(`Failed to fetch word list: ${response.status}`);
}
const raw = await response.text();

const words = new Set();
for (const line of raw.split("\n")) {
  const token = line.replace(/\r/g, "").trim().toLowerCase();
  if (/^[a-z']+$/.test(token)) {
    words.add(token);
  }
}

const sorted = [...words].sort();
const body = sorted.join("\n");

const file = `// Generated by scripts/buildSafeWords.mjs. Do not edit by hand.
// Source: ${SOURCE}
// ${sorted.length} human verified plain English tokens.

export const SAFE_WORDS_RAW = ${JSON.stringify(body)};

export const SAFE_WORDS: ReadonlySet<string> = new Set(SAFE_WORDS_RAW.split("\\n"));
`;

await mkdir(dirname(target), { recursive: true });
await writeFile(target, file, "utf8");
console.log(`Wrote ${sorted.length} words to ${target}`);
